---
- name: Get docker interfaces names
  command: >-
    find /sys/class/net -type l
    \( -name 'br-*' -o -name 'docker*' \)
    -printf '%f\n'
  register: _docker_bridge_interfaces
  changed_when: false
  check_mode: false

- name: Store DOCKER chain rules
  set_fact:
    firewall_docker_rules: >-
      {%- set rules=[] %}

      {%- for line in _docker_bridge_interfaces.stdout_lines %}
          {%- set _=rules.append('-I INPUT -i %s -j ACCEPT' % line) -%}
      {%- endfor -%}

      {{ rules }}


- debug: var=firewall_docker_rules
