---
- name: Converge
  hosts: all
  become: true

  vars:
    firewall_ipv6: false
    firewall_allowed_tcp_ports:
      - "9123"
      - port: 1042
        allow: 8.8.8.8
        deny: true

      - port: 1043
        allow:
          - 10.0.0.42/24
          - 10.0.0.1/24
        deny:
          - 10.0.0.5/24

      - port: 1044
        allow: 10.0.0.1
        deny: 10.0.0.5/24

    firewall_allowed_udp_ports:
      - "9123"
      - port: 1042
        allow: 8.8.8.8
        deny: true

      - port: 1043
        allow:
          - 10.0.0.42/24
          - 10.0.0.1/24
        deny:
          - 10.0.0.5/24

      - port: 1044
        allow: 10.0.0.1
        deny: 10.0.0.5/24


  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=1200
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-firewall
